name: Deploy Godot Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Instalar Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: "4.7.2"
          use-dotnet: false

      - name: Exportar Web
        run: |
          mkdir -p dist
          godot --headless --export-release "Web" dist/index.html
